services:
  - type: web
    name: rnsambe-malawi-school-reporting
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PYTHONPATH
        value: .
    autoDeploy: false